### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jakee246/project6#1]
Nice use of `content_for`! Unfortunately, it looks like there's a [stray `</div>` tag in your layout](https://github.com/jakee246/project6/blob/master/views/layout.erb#L17), throwing [an HTML validation error](http://validator.w3.org/check?uri=https%3A%2F%2Ftc359project6.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0). Can you fix this?

**Comment by jakee246** [comment]
Fixed project6 issue. HTML validates correctly now. Working on previous
project issue.

Thank you, Jake

**Comment by chrisvfritz** [comment]
:+1: Looks good.
